title: My personal blog - Lawrence Karanja
email: lawrenslava1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Lawrence Karanja and you have found my blog. I am a Web and Android Apps developer who
  also knows about networking. I love to experiment with different technologies, travel, play chess and I also read...A lot.
  I will use this blog to share some the things I'm currently doing,reading and also use it as a personal portforlio.
permalink: ':title/'

url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Lawrence Karanja # add your name
author-pic: adam-face.jpg
about-author: My name is Lawrence Karanja. I’m a WEB DEVELOPER,Android Developer, and now a blogger. I love travelling, listening to music, watching movies and reading books.

# Contact links
email: lawrenslava1@gmail.com# Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: lawrence254 # Add your Github handle
twitter: '@lawremkenya' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
